Lion tracker to master merge evaluation
IRNAS/smartparks-rhino-tracker-firmware pull request #17
Opened 2019-12-11 18:48 UTC by SloMusti

2019-12-11 19:02 UTC, VojislavM commented on src/board.h
> +
add #endif

2019-12-11 19:06 UTC, VojislavM requested changes
change endif

2019-12-11 19:08 UTC, SloMusti commented on src/board.h
> +
Fixed.

2019-12-11 19:09 UTC, VojislavM approved these changes

2019-12-12 11:36 UTC, acegne approved these changes

2019-12-12 11:36 UTC, acegne approved these changes

2019-12-12 11:42 UTC, acegne approved these changes

2019-12-12 11:43 UTC, acegne approved these changes

2019-12-12 11:43 UTC, acegne approved these changes

2019-12-12 11:43 UTC, acegne approved these changes

2019-12-12 11:44 UTC, acegne approved these changes

2019-12-12 14:01 UTC, acegne approved these changes

2019-12-12 14:01 UTC, acegne approved these changes

2019-12-12 20:14 UTC, merged